name: Codecov

on:
  push:
    branches:
      - main
  pull_request:

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
         CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}