/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

interface IOlpManagerUtils {
    function init(address vault, address positions_manager, address shorts_tracker, address olp) external;

    function setShortsTrackerAveragePriceWeight(uint256 weight) external;

    function getPrice() external view returns (uint256);

    function getAumInUsdo() external view returns (uint256);

    function getAum() external view returns (uint256);

    function getGlobalShortDelta(address token, uint256 price, uint256 size) external view returns (uint256, bool);

    function getGlobalShortAveragePrice(address token) external view returns (uint256);
}
