/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

interface IFundingRateManager {
    function init(address gov, address vault) external;

    function setGov(address gov) external;

    function cumulativeFundingRate(address token) external view returns (uint256);

    function getNextFundingRate(address token) external view returns (uint256);

    function updateCumulativeFundingRate(address collateral_token) external;
}
