/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

interface IPositionsDecreaseRouter {
    function init(address weth, address vault, address positions_decrease_manager, address swap_router) external;

    function decreasePosition(address collateral_token, address index_token, uint256 collateral_delta, uint256 size_delta, bool is_long, address receiver, uint256 price) external returns (uint256);

    function decreasePositionEth(address collateral_token, address index_token, uint256 collateral_delta, uint256 size_delta, bool is_long, address receiver, uint256 price) external returns (uint256);
}
