/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

interface ITimeDistributor {
    function init() external;

    function setGov(address gov) external;

    function setTokensPerInterval(address receiver, uint256 amount) external;

    function updateLastDistributionTime(address receiver) external;

    function setDistribution(address[] memory receivers, uint256[] memory amounts, address[] memory reward_tokens) external;

    function distribute() external returns (uint256);

    function getRewardToken(address receiver) external view returns (address);

    function getDistributionAmount(address receiver) external view returns (uint256);

    function getIntervals(address receiver) external view returns (uint256);
}
