/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

interface IPositionsIncreaseRouter {
    function init(address weth, address vault, address positions_increase_manager, address swap_router) external;

    function increasePosition(address[] memory path, address index_token, uint256 amount_in, uint256 min_out, uint256 size_delta, bool is_long, uint256 price) external;

    function increasePositionEth(address[] memory path, address index_token, uint256 min_out, uint256 size_delta, bool is_long, uint256 price) external payable;
}
