/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

interface IYieldTracker {
    function init(address gov, address yield_token) external;

    function setGov(address gov) external;

    function setDistributor(address distributor) external;

    function claim(address account, address receiver) external returns (uint256);

    function getTokensPerInterval() external view returns (uint256);

    function claimable(address account) external view returns (uint256);

    function updateRewards(address account) external;
}
