/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

interface IOlpManager {
    function init(address gov, address olp_manager_utils, address vault, address swap_manager, address positions_manager, address shorts_tracker, address usdo, address olp) external;

    function isHandler(address account) external view returns (bool);

    function setGov(address gov) external;

    function setInPrivateMode(bool in_private_mode) external;

    function setHandler(address handler, bool is_active) external;

    function addLiquidity(address token, uint256 amount, uint256 min_usdo, uint256 min_olp) external returns (uint256);

    function addLiquidityForAccount(address funding_account, address account, address token, uint256 amount, uint256 min_usdo, uint256 min_olp) external returns (uint256);

    function removeLiquidity(address token_out, uint256 olp_amount, uint256 min_amount, address recipient) external returns (uint256);

    function removeLiquidityForAccount(address account, address token_out, uint256 olp_amount, uint256 min_amount, address recipient) external returns (uint256);
}
