/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

interface IOrderbookIncrease {
    function init(address gov, address increase_router) external;

    function getCurrentIndex(address account) external view returns (uint256);

    function createIncreaseOrder(uint256 collateral_amount, address collateral_token, address index_token, uint256 size_delta, bool is_long, uint256 trigger_price, bool trigger_above_threshold, uint256 execution_fee) external payable;

    function cancelIncreaseOrder(uint256 order_index) external;

    function getIncreaseOrder(address account, uint256 order_index) external view returns (address, uint256, address, address, uint256, bool, uint256, bool, uint256);
}
