/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

interface ISwapRouter {
    function init(address weth, address usdo, address vault, address swap_manager, address positions_router) external;

    function directPoolDeposit(address token, uint256 amount) external;

    function swapForPosition(address[] memory path, uint256 min_out, address receiver) external returns (uint256);

    function swap(address[] memory path, uint256 amount_in, uint256 min_out, address receiver) external;

    function swapEthToTokens(address[] memory path, uint256 min_out, address receiver) external payable;

    function swapToEth(address token_in, uint256 amount_in, uint256 min_out, address receiver) external;
}
