/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

interface ISwapManager {
    function init(address gov, address usdo, address vault, address fee_manager, address funding_rate_manager) external;

    function setInManagerMode(bool in_manager_mode) external;

    function setManager(address account, bool is_manager) external;

    function usdoAmount(address token) external view returns (uint256);

    function buyUsdo(address token, address receiver) external returns (uint256);

    function sellUsdo(address token, address receiver) external returns (uint256);

    function swap(address token_in, address token_out, address receiver) external returns (uint256);
}
