/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

interface IPositionsLiquidationManager {
    function init(address gov, address vault, address vault_utils, address fee_manager, address funding_rate_manager, address positions_manager, address positions_manager_utils, address positions_decrease_manager) external;

    function setGov(address gov) external;

    function setLiquidator(address liquidator, bool is_active) external;

    function liquidatePosition(address account, address collateral_token, address index_token, bool is_long, address fee_receiver) external;
}
