/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

interface IRewardRouter {
    function init(address gov, address omx, address es_omx, address bn_omx, address olp, address staked_omx_tracker, address bonus_omx_tracker, address staked_omx_tracker_staking, address bonus_omx_tracker_staking, address fee_omx_tracker_staking, address fee_olp_tracker_staking, address staked_olp_tracker_staking, address olp_manager) external;

    function setGov(address gov) external;

    function batchStakeOmxForAccount(address[] memory accounts, uint256[] memory amounts) external;

    function stakeOmxForAccount(address account, uint256 amount) external;

    function stakeOmx(uint256 amount) external;

    function stakeEsOmx(uint256 amount) external;

    function unstakeOmx(uint256 amount) external;

    function unstakeEsOmx(uint256 amount) external;

    function mintAndStakeOlp(address token, uint256 amount, uint256 min_usdo, uint256 min_olp) external returns (uint256);

    function unstakeAndRedeemOlp(address token_out, uint256 olp_amount, uint256 min_out, address receiver) external returns (uint256);

    function claim() external;

    function claimEsOmx() external;

    function claimFees() external;

    function compound() external;

    function compoundForAccount(address account) external;

    function batchCompoundForAccounts(address[] memory accounts) external;
}
