/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

interface IShortsTracker {
    function init(address gov, address vault, address vault_utils, address positions_manager) external;

    function setGov(address gov) external;

    function setHandler(address handler, bool is_active) external;

    function setIsGlobalShortDataReady(bool value) external;

    function updateGlobalShortData(address account, address collateral_token, address index_token, bool is_long, uint256 size_delta, uint256 mark_price, bool is_increase) external;

    function getGlobalShortDelta(address token) external view returns (bool, uint256);

    function setInitData(address[] memory tokens, uint256[] memory average_prices) external;

    function getNextGlobalShortData(address account, address collateral_token, address index_token, uint256 next_price, uint256 size_delta, bool is_increase) external view returns (uint256, uint256);

    function getRealisedPnl(address account, address collateral_token, address index_token, uint256 size_delta, bool is_increase) external view returns (int256);
}
