/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

interface IVaultPriceFeed {
    function init(address gov, uint256 max_strict_price_deviation) external;

    function setGov(address gov) external;

    function setAdjustment(address token, bool is_additive, uint256 adjustment_bps) external;

    function setPrice(address token, uint256 price) external;

    function setSpreadBasisPoints(address token, uint256 spread_basis_points) external;

    function setMaxStrictPriceDeviation(uint256 max_strict_price_deviation) external;

    function setTokenConfig(address token, bool is_strict_stable) external;

    function getPrice(address token, bool maximize) external view returns (uint256);

    function getPriceV1(address token, bool maximize) external view returns (uint256);

    function getPrimaryPrice(address token, bool _maximize) external view returns (uint256);
}
